### ISSUE TITLE
Large Steps in Cloth Simulation (Baraff, 1998)

### ISSUE THREAD

**Issue by pjhjohn** [pjhjohn/wednesday-milestone#72]

**Comment by pjhjohn** [comment]
[Candidates]
- Large Steps in Cloth Simulation (Baraff, 1998)
- Stable but Responsive Cloth (Choi & Ko, 2002)
- Simulation of Clothing with Folds and Wrinkles (Bridson, 2003)
- Simple, yet Accurate Nonlinear Tensile Stiffness (Volino, 2009)
- Plausible cloth animation using dynamic bending model (Zhou, 2008)
- Discrete Shells (Grinspun, 2003)
- Collision and self-collision handling in cloth model dedicated to design garments (Provot, 1997)
- Robust Treatment of Collisions, Contact and Friction for Cloth Animation (Bridson, 2002)
- Untangling Cloth (Baraff, 2003)
- Collision Detection for Deformable Object (Teschner, 2004)
- Interactive Continuous Collision Detection between eformable Models using Connectivity-Based Culling (Tang, 2008)
- Fast Collision Detection for Deformable Models using Representative-Triangles (Curtis, 2008)
- Fast Continuous Collision Detection using Deforming Non-penetration Filters (Tang, 2010)
- ICM (Volino, 2006) / MICM (Ye, 2012)
- Optimized Spatial Hashing for Collision Detection of Deformable Objects (Teschner, 2003)

**Comment by pjhjohn** [comment]
너무 옛날이지 않은걸로 찾아보자.

**Comment by pjhjohn** [comment]
[Large Steps in Cloth Simulation (Baraff, 1998)](http://www.cs.cmu.edu/~baraff/papers/sig98.pdf)

**Comment by pjhjohn** [comment]
일단 밤 새고 있는데, 9시간 후에 발표니까 그 전까진 뭐라도 하지 않을까??제발??준호야??

**Comment by pentatracy5** [comment]
Hello. I want to handle the collision between cloth and rigidbody. It seems like level set method is the most popular way. However, this method is new to me. I've been reading the papers referred in "Simulation of Clothing with Folds and Wrinkles" but it is still hard for me to understand. So could you please recommend some materials which is easier? Papers, courses or code, anything will be fine. Or could you please introduce the main implementation idea of level set method? Thanks so much.
